### ISSUE TITLE
Doesn't even install

### ISSUE THREAD

**Issue by Goury** [cc-d/flask-simple-captcha#12]
ERROR: flask 2.1.1 has requirement Werkzeug>=2.0, but you'll have werkzeug 0.16.0 which is incompatible.

**Comment by tiwe0** [comment]
Hi, I just had the same problem. 
I fixed it by modifying the setup.py
```python
install_requires=['Werkzeug>=0.16.0', 'Pillow>=6.1.0']
```
then, install it
```bash
python3 setup.py install
```
It seems that there are no conflicts, but I do not test it completely.
English is not my home language. If there is any problem, just tell me.
Good Luck!

**Comment by cc-d** [comment]
Hey, sorry guys I don't check github often, I'll look into it tonight.

**Comment by cc-d** [comment]
The error didn't replicate for me, but if that change worked for you guys, it's harmless so I'll add it in anyway. I think I'll have to update the package too on pypi.

**Comment by cc-d** [comment]
Okay, I added that change and updated pypi. Closing for now, if you guys still have issues, feel free to re-open.
