### ISSUE TITLE
Confusing line: CAPTCHA = CAPTCHA(config=config.CAPTCHA_CONFIG)

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [cc-d/flask-simple-captcha#15]
This line is very confusing

```
CAPTCHA = CAPTCHA(config=config.CAPTCHA_CONFIG)
```

I thought config.CAPTCHA_CONFIG meant current_app.CAPTCHA_CONFIG

**Comment by cc-d** [comment]
you're welcome to open a PR :)

**Comment by cc-d** [comment]
im fixing this in the version im publishign today.
