### ISSUE TITLE
Planned support for Werkzeug >3

### ISSUE THREAD

**Issue by atnjqt** [cc-d/flask-simple-captcha#25]
Finding that the helpful `flask-simple-catpcha` isn't compatible with [Flask > 3](https://pypi.org/project/Flask/) given the dependency for [Werkzeug >3](https://pypi.org/project/Werkzeug/). 

Curious if there is a roadmap to Flask v3 compatibility! I get the following:

```bash
ERROR: flask-simple-captcha 5.5.3 has requirement Werkzeug<3,>=0.16.0, but you'll have werkzeug 3.0.1 which is incompatible.
```
Best

**Comment by cc-d** [comment]
Oh, I should be able to fix this just by broadening the requirements a little bit, I'll just broaden the package version range. Thanks for reporting this.

**Comment by cc-d** [comment]
I removed the upper limit on the versioning, might be a decision I regret later, but I tested this running the tests  and verified a submitted captcha w/ the debug server, seems to work fine. I'll publish the next version now.

```
---------- coverage: platform darwin, python 3.11.5-final-0 ----------
Name                                         Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------
flask_simple_captcha/__init__.py                 3      0   100%
flask_simple_captcha/captcha_generation.py      78      0   100%
flask_simple_captcha/config.py                  10      0   100%
flask_simple_captcha/img.py                     58      0   100%
flask_simple_captcha/text.py                    25      0   100%
flask_simple_captcha/utils.py                   51      0   100%
--------------------------------------------------------------------------
TOTAL                                          225      0   100%


================== 41 passed in 2.06s
```
