### ISSUE TITLE
Minor typo in the README examples

### ISSUE THREAD

**Issue by amirstm** [cc-d/flask-simple-captcha#27]
Hey. Thank you for your great library.
There is a minor typo in the **Protecting a Route** sample code in the projects **README** file. In the fifth line a _return_ keyword should be added:
` return render_template("example.html", captcha=new_captcha_dict)`
 The code as it is raises an error saying:
`TypeError: The view function for 'example' did not return a valid response. The function either returned None or ended without a return statement.`

**Comment by cc-d** [comment]
Feel free to open a PR :) I'm on mobile as of writing this comment, so I can't see if there's one open.

In this case, example.html is the name of an example template, I'm not even sure what could be used as an example template that wouldn't have that error. Any ideas?

**Comment by cc-d** [comment]
Oh I see what you mean. I misunderstood what you meant yesterday.

It's missing a return keyword, which should be there regardless even if it's an example. I understand now why that could be an issue!

I'll update the example in the README to have that return keyword + I'll make the template names consistent. Thank you for raising this issue.

**Comment by cc-d** [comment]
I updated the README.md example to have the return keyword, plus made the example template naming consistent across both codeblocks. I'll close this issue for now, and I apologize for misunderstanding what you meant the first time around :)
